### ISSUE TITLE
Failing to select any user/config.

### ISSUE THREAD

**Issue by Threpio** [matsuyoshi30/gitsu#11]
Version: gitsu 0.2.1
Medium: Homebrew

Please find attached a small screencapture of the error.

https://user-images.githubusercontent.com/49570057/124137509-0805c200-da86-11eb-8cd9-3de4c9a8b6b3.mov

**Comment by matsuyoshi30** [comment]
@Threpio Thanks for reporting. I'll take a look later.

**Comment by matsuyoshi30** [comment]
I think it relates to gpg. Do you use it with gpg-key?

**Comment by Threpio** [comment]
I used Homebrew to install - Not sure what you mean with gpg-key ( I will admit I am new to golang )

Are there more local logs it creates that I can provide you with?

**Comment by Threpio** [comment]
I did not manage to get the gpg-key command working but nor do I know what it does/mean...

**Comment by Threpio** [comment]
UPDATE: Seems that it might be an issue with it's interaction with my zsh, ITERM setup.

Does not work in Iterm2.
Does work within the goland terminal of a downloaded and build gitsu project (latest branch of master/main)

Might be an old build and something has already fixed it?

https://user-images.githubusercontent.com/49570057/124176383-2207ca80-daaf-11eb-8bc4-e369f8a334f7.mov

**Comment by matsuyoshi30** [comment]
I've just figured out what happened.

`git su` command expects to be run under the git project directory. Are you running the command somewhere other than under a git project?

**Comment by Threpio** [comment]
Ahhh yes. That could be the problem. 

The iterm example above is outside and then the goland variable is inside a git folder.

Might be worth mentioning it in the readme to prevent idiots like me doing this again!
