### ISSUE TITLE
cannot switch user,exit status 128

### ISSUE THREAD

**Issue by SJFCS** [matsuyoshi30/gitsu#22]
![image](https://user-images.githubusercontent.com/36468758/190374189-dbacb420-cd9e-4c69-af1e-56407f0b4e1e.png)
❯ git -v
git version 2.37.3
❯ uname -r
5.15.67-1-lts

**Comment by Techassi** [comment]
Exit status 128 is a Git status code. It's most likely you executed `gitsu` in a folder which is not a Git repository (missing `.git` folder).
