### ISSUE TITLE
Add ability to name users, and change via command line

### ISSUE THREAD

**Issue by BrendanThompson** [matsuyoshi30/gitsu#5]
It would be ideal if we were able to give an alias for each user, and then change to that use via command line. For example:

```
$ git su meow
```

This would then set the git user and email associated with the alias `meow`.

**Comment by matsuyoshi30** [comment]
It sounds good. Thanks for giving a cool idea!

**Comment by l3str4nge** [comment]
Hello,  I want to contribute so could I take this issue if nobody working on this yet ? :)

**Comment by matsuyoshi30** [comment]
@mateuszz0000 Of course. I hope you'll give it a try!

**Comment by BrendanThompson** [comment]
@matsuyoshi30 any timeframe as to when this will get released?

**Comment by matsuyoshi30** [comment]
@BrendanThompson I've just released new version!
